const forceCollide = 0
const distanceViaLayer = [170, 120, 80, 50]
// const forceCollide = 20
// const distanceViaLayer = [100, 80, 60, 20]
const group = {
  JavaScript: 0,
  Introduction: 1,
  Grammer: 2,
  Expression: 3,
  Controlflow: 4,
  ForLoop: 5,
  Function: 6,
  Browser: 7,
}
const data = {
  nodes: [
    {id: "JavaScript", text: "JavaScript", title: "JavaScript", group: group['JavaScript'] , important: 20},
      {id: "簡介", text: "簡介", title: "Introduction", group: group['Introduction'], important: 10},
        {id: "起源", text: "起源", title: "Origin", group: group['Introduction'], important: 10},
        {id: "ECMAScript", text: "ECMAScript", title: "ECMAScript", group: group['Introduction'], important: 10},
        {id: "相關工具", text: "相關工具", title: "Tools", group: group['Introduction'], important: 10},
          {id: "文字編輯器", text: "文字編輯器", title: "Text Editor", group: group['Introduction'], important: 10},
            {id: "VSCode", text: "VSCode", title: "VSCode", group: group['Introduction'], important: 10},
            {id: "Sublime", text: "Sublime", title: "Sublime", group: group['Introduction'], important: 10},
            {id: "WebStorm", text: "WebStorm", title: "WebStorm", group: group['Introduction'], important: 10},
            {id: "XCode", text: "XCode", title: "XCode", group: group['Introduction'], important: 10},
          {id: "版控相關", text: "版控相關", title: "Version Control", group: group['Introduction'], important: 10},
            {id: "Git", text: "Git", title: "Git", group: group['Introduction'], important: 10},
            {id: "GitHub", text: "GitHub", title: "GitHub", group: group['Introduction'], important: 10},
            {id: "Sourcetree", text: "Sourcetree", title: "Sourcetree", group: group['Introduction'], important: 10},
      {id: "基礎語法", text: "基礎語法", title: "Grammer", group: group['Grammer'], important: 10},
        {id: "註解", text: "註解", title: "Comment", group: group['Grammer'], important: 10},
        {id: "宣告", text: "宣告", title: "Declare", group: group['Grammer'], important: 10},
        {id: "資料型別", text: "資料型別", title: "Data Types", group: group['Grammer'], important: 10},
          {id: "原始型別", text: "原始型別", title: "Primitive Types", group: group['Grammer'], important: 10},
            {id: "字串型別", text: "字串", title: "String", group: group['Grammer'], important: 10},
            {id: "數字型別", text: "數字", title: "String", group: group['Grammer'], important: 10},
            {id: "布林值型別", text: "布林值", title: "String", group: group['Grammer'], important: 10},
            {id: "null型別", text: "null", title: "null", group: group['Grammer'], important: 10},
            {id: "undefined型別", text: "undefined", title: "Strundefineding", group: group['Grammer'], important: 10},
          {id: "非原始型別", text: "非原始型別", title: "Non-Primitive Types", group: group['Grammer'], important: 10},
            {id: "物件型別", text: "物件", title: "Object", group: group['Grammer'], important: 10},
            {id: "陣列型別", text: "陣列", title: "Array", group: group['Grammer'], important: 10},
            {id: "函式型別", text: "函式", title: "Function", group: group['Grammer'], important: 10},
            {id: "不是原始型別", text: "不是原始型別", title: "Not Primitive Types", group: group['Grammer'], important: 10},
    {id: "運算", text: "運算", title: "Expression", group: group['Expression'], important: 10},
      {id: "運算子", text: "運算子", title: "Operator", group: group['Expression'], important: 10},
        {id: "賦值運算子", text: "賦值運算子", title: "Assignment Operator", group: group['Expression'], important: 10},
        {id: "算術運算子", text: "算術運算子", title: "Arithmetic Operator", group: group['Expression'], important: 10},
        {id: "比較運算子", text: "比較運算子", title: "Comparison Operator", group: group['Expression'], important: 10},
        {id: "位元運算子", text: "位元運算子", title: "Bitwise Operator", group: group['Expression'], important: 1},
        {id: "邏輯運算子", text: "邏輯運算子", title: "Logical Operator", group: group['Expression'], important: 10},
        {id: "字串運算子", text: "字串運算子", title: "String Operator", group: group['Expression'], important: 10},
        {id: "三元運算子", text: "三元運算子", title: "Conditional (ternary) Operator", group: group['Expression'], important: 10},
        {id: "逗點運算子", text: "逗點運算子", title: "Comma Operator", group: group['Expression'], important: 10},
        {id: "一元運算子", text: "一元運算子", title: "Unary Operator", group: group['Expression'], important: 10},
        {id: "關係運算子", text: "關係運算子", title: "Relational Operator", group: group['Expression'], important: 10},
    {id: "流程控制", text: "流程控制", title: "Control flow", group: group['Controlflow'], important: 10},
      {id: "if/else", text: "if/else", title: "if/else", group: group['Controlflow'], important: 10},
      {id: "switch", text: "switch", title: "switch", group: group['Controlflow'], important: 10},
    {id: "迴圈", text: "迴圈", title: "Loop", group: group['ForLoop'], important: 10},
      {id: "For迴圈", text: "For Loop", title: "For Loop", group: group['ForLoop'], important: 10},
      {id: "While迴圈", text: "While", title: "While", group: group['ForLoop'], important: 10},
    {id: "函式", text: "函式", title: "Function", group: group['Function'], important: 10},
      {id: "宣告函式", text: "宣告函式", title: "Declare Function", group: group['Function'], important: 10},
      {id: "函式引數", text: "函式引數", title: "Argument", group: group['Function'], important: 10},
      {id: "函式參數", text: "函式參數", title: "Parameter", group: group['Function'], important: 10},
      {id: "回呼函式", text: "回呼函式", title: "Callback Function", group: group['Function'], important: 10},
      {id: "閉包", text: "閉包", title: "Closure", group: group['Function'], important: 10},
      {id: "遞迴", text: "遞迴", title: "Recursive", group: group['Function'], important: 10},
      {id: "箭頭函式", text: "箭頭函式", title: "Arrow Function", group: group['Function'], important: 10},
    {id: "瀏覽器", text: "瀏覽器", title: "Browser", group: group['Browser'], important: 10},
      {id: "瀏覽器物件模型", text: "瀏覽器物件模型", title: "Browser Object Model", group: group['Browser'], important: 10},
      {id: "瀏覽器事件", text: "瀏覽器事件", title: "Browser Event", group: group['Browser'], important: 10},
      {id: "資源請求", text: "資源請求", title: "Request", group: group['Browser'], important: 10},
      {id: "儲存機制", text: "儲存機制", title: "Web Storage", group: group['Browser'], important: 10},
      {id: "垃圾回收機制", text: "垃圾回收機制", title: "Garbage Collection", group: group['Browser'], important: 10},
  ],
  links: [
    {target: "JavaScript", source: "簡介", value: 1, distance: distanceViaLayer[0]},
      {target: "簡介", source: "起源", value: 1, distance: distanceViaLayer[1]},
      {target: "簡介", source: "ECMAScript", value: 1, distance: distanceViaLayer[1]},
      {target: "簡介", source: "相關工具", value: 1, distance: distanceViaLayer[1]},
        {target: "相關工具", source: "文字編輯器", value: 1, distance: distanceViaLayer[2]},
          {target: "文字編輯器", source: "VSCode", value: 1, distance: distanceViaLayer[3]},
          {target: "文字編輯器", source: "Sublime", value: 1, distance: distanceViaLayer[3]},
          {target: "文字編輯器", source: "WebStorm", value: 1, distance: distanceViaLayer[3]},
          {target: "文字編輯器", source: "XCode", value: 1, distance: distanceViaLayer[3]},
        {target: "相關工具", source: "版控相關", value: 1, distance: distanceViaLayer[2]},
          {target: "版控相關", source: "Git", value: 1, distance: distanceViaLayer[3]},
          {target: "版控相關", source: "GitHub", value: 1, distance: distanceViaLayer[3]},
          {target: "版控相關", source: "Sourcetree", value: 1, distance: distanceViaLayer[3]},
    {target: "JavaScript", source: "基礎語法", value: 1, distance: distanceViaLayer[0]},
      {target: "基礎語法", source: "註解", value: 1, distance: distanceViaLayer[1]},
      {target: "基礎語法", source: "宣告", value: 1, distance: distanceViaLayer[1]},
      {target: "基礎語法", source: "資料型別", value: 1, distance: distanceViaLayer[1]},
        {target: "資料型別", source: "原始型別", value: 1, distance: distanceViaLayer[2]},
          {target: "原始型別", source: "字串型別", value: 1, distance: distanceViaLayer[3]},
          {target: "原始型別", source: "數字型別", value: 1, distance: distanceViaLayer[3]},
          {target: "原始型別", source: "布林值型別", value: 1, distance: distanceViaLayer[3]},
          {target: "原始型別", source: "null型別", value: 1, distance: distanceViaLayer[3]},
          {target: "原始型別", source: "undefined型別", value: 1, distance: distanceViaLayer[3]},
        {target: "資料型別", source: "非原始型別", value: 1, distance: distanceViaLayer[2]},
          {target: "非原始型別", source: "物件型別", value: 1, distance: distanceViaLayer[3]},
          {target: "非原始型別", source: "陣列型別", value: 1, distance: distanceViaLayer[3]},
          {target: "非原始型別", source: "函式型別", value: 1, distance: distanceViaLayer[3]},
          {target: "非原始型別", source: "不是原始型別", value: 1, distance: distanceViaLayer[3]},
    {target: "JavaScript", source: "運算", value: 1, distance: distanceViaLayer[0]},
      {target: "運算", source: "運算子", value: 1, distance: distanceViaLayer[1]},
        {target: "運算子", source: "賦值運算子", value: 1, distance: distanceViaLayer[2]},
        {target: "運算子", source: "算術運算子", value: 1, distance: distanceViaLayer[2]},
        {target: "運算子", source: "比較運算子", value: 1, distance: distanceViaLayer[2]},
        {target: "運算子", source: "位元運算子", value: 1, distance: distanceViaLayer[2]},
        {target: "運算子", source: "邏輯運算子", value: 1, distance: distanceViaLayer[2]},
        {target: "運算子", source: "字串運算子", value: 1, distance: distanceViaLayer[2]},
        {target: "運算子", source: "三元運算子", value: 1, distance: distanceViaLayer[2]},
        {target: "運算子", source: "逗點運算子", value: 1, distance: distanceViaLayer[2]},
        {target: "運算子", source: "一元運算子", value: 1, distance: distanceViaLayer[2]},
        {target: "運算子", source: "關係運算子", value: 1, distance: distanceViaLayer[2]},
    {target: "JavaScript", source: "流程控制", value: 1, distance: distanceViaLayer[0]},
      {target: "流程控制", source: "if/else", value: 1, distance: distanceViaLayer[1]},
      {target: "流程控制", source: "switch", value: 1, distance: distanceViaLayer[1]},
    {target: "JavaScript", source: "迴圈", value: 1, distance: distanceViaLayer[0]},
      {target: "迴圈", source: "For迴圈", value: 1, distance: distanceViaLayer[1]},
      {target: "迴圈", source: "While迴圈", value: 1, distance: distanceViaLayer[1]},
    {target: "JavaScript", source: "函式", value: 1, distance: distanceViaLayer[0]},
      {target: "函式", source: "宣告函式", value: 1, distance: distanceViaLayer[1]},
      {target: "函式", source: "函式引數", value: 1, distance: distanceViaLayer[1]},
      {target: "函式", source: "函式參數", value: 1, distance: distanceViaLayer[1]},
      {target: "函式", source: "回呼函式", value: 1, distance: distanceViaLayer[1]},
      {target: "函式", source: "閉包", value: 1, distance: distanceViaLayer[1]},
      {target: "函式", source: "遞迴", value: 1, distance: distanceViaLayer[1]},
      {target: "函式", source: "箭頭函式", value: 1, distance: distanceViaLayer[1]},
    {target: "JavaScript", source: "瀏覽器", value: 1, distance: distanceViaLayer[0]},
      {target: "瀏覽器", source: "瀏覽器物件模型", value: 1, distance: distanceViaLayer[1]},
      {target: "瀏覽器", source: "瀏覽器事件", value: 1, distance: distanceViaLayer[1]},
      {target: "瀏覽器", source: "資源請求", value: 1, distance: distanceViaLayer[1]},
      {target: "瀏覽器", source: "儲存機制", value: 1, distance: distanceViaLayer[1]},
      {target: "瀏覽器", source: "垃圾回收機制", value: 1, distance: distanceViaLayer[1]},
  ]
}
